### ISSUE TITLE
Weapon Pick Up 

### ISSUE THREAD

**Issue by hoodz123** [cadburry6969/cad-gundrop#2]
Im Running Latest Qb Core And Just Wondering How We Get The Weapons From The Crates?

**Comment by shadowTW** [comment]
you fixed it?

**Comment by hoodz123** [comment]
Bruh I made a who need script I took bits of his code but yeah I spoke to him in dc he said he didn’t have plans on updating so yeah I did what I had todo I can pass it you free of charge you might be able to clean it up a little 👏🏽

**Comment by cadburry6969** [comment]
if you are interested in maintaining it, ill add you as a collaborator
