### ISSUE TITLE
Airdrop stuck in the air

### ISSUE THREAD

**Issue by Veolene** [cadburry6969/cad-gundrop#4]
![image](https://user-images.githubusercontent.com/53438206/186784760-5e164908-59de-44a8-a190-26c53c07e200.png)

Airdrop is stuck in the air after consuming the redphone

**Comment by cadburry6969** [comment]
are there any errors on client/server?

**Comment by Veolene** [comment]
> are there any errors on client/server?

I got no errors from serverside and clientside, but I did a clean framework install and it seems to be working. this may have happened because i was on a very old version of qbcore. Thank you for responding so quickly though!
