### ISSUE TITLE
Half works

### ISSUE THREAD

**Issue by Soldierofthelam** [cadburry6969/cad-gundrop#5]
Phones do call drop,
 drop doesn't initiate the plane 
plane never comes no errors on server console or F8

**Comment by cadburry6969** [comment]
It works perfectly for me, you can test it on my server 
Test Server IP: 147.189.171.202:30120

**Comment by Soldierofthelam** [comment]
I have no doubt it does but without getting errors on my server I can't problem shoot why its not calling the drop

**Comment by cadburry6969** [comment]
are you on the latest version? Are you using any radio given in the resource? 
you might have changed something or else something in your server is conflicting with it.
also, try with one sync on

**Comment by Soldierofthelam** [comment]
Yea I'm on the latest version of Qbcore using the new exports not events So what I did was change the config file to operated under old or new using this code now it works good.
  I appreciate your responses and help in trying to resolve the matter.

"example code"
Config = {}

Config['General'] = {
    ["Core"] = "QBCORE", -- This can be ESX , QBCORE , NPBASE
    ["SQLWrapper"] = "oxmysql", -- This can be `| oxmysql or ghmattimysql or mysql-async
}


Config['CoreSettings'] = {
    ["QBCORE"] = {
        ["Version"] = "new", -- new = using export | old = using events
        ["Export"] = exports['qb-core']:GetCoreObject(), -- uncomment this if using new qbcore version
        ["Trigger"] = "QBCore:GetObject",
        ["HasItem"] = "QBCore:HasItem", -- Imporant [ Your trigger for checking has item, default is CORENAME:HasItem ] 
        ["ServerNotificationEvent"] = "QBCore:Notify", 

    }, 
}
![20221124121930_1](https://user-images.githubusercontent.com/117047687/203839794-2d96b91f-4153-4c67-85ad-0246e2d9c59d.jpg)

![20221124121941_1](https://user-images.githubusercontent.com/117047687/203839858-05f065ff-2347-4061-8241-6b79de59ffa1.jpg)

![20221124121948_1](https://user-images.githubusercontent.com/117047687/203839878-90341c5d-71a2-4c98-bdc9-c127ff71602c.jpg)

![20221124122223_1](https://user-images.githubusercontent.com/117047687/203839943-aa905b83-0043-4a6a-81f4-33b270a25e13.jpg)

![20221124122323_1](https://user-images.githubusercontent.com/117047687/203839967-ad77a877-3600-429a-9845-5241a7c5088e.jpg)

![20221124122327_1](https://user-images.githubusercontent.com/117047687/203840086-47d2fb37-2270-4423-a379-62db09579adc.jpg)

--SMG received and on back--

![20221124122814_1](https://user-images.githubusercontent.com/117047687/203840313-7f9fe595-2441-4744-84f1-467d00b03953.jpg)

**Comment by cadburry6969** [comment]
> 

I was asking about the latest of my resource anyway leave that so now it's perfectly working for you, right?

**Comment by Soldierofthelam** [comment]
Yea as far as I can tell yea with no errors
