### ISSUE TITLE
box bugs out if it hits something on the way down

### ISSUE THREAD

**Issue by Krisb239** [cadburry6969/cad-gundrop#6]
If the box hits something on the way down the parachute wont despawn and you cant search the box. I'm not getting any errors. It's like the box itself bugs out.

**Comment by cadburry6969** [comment]
could you provide a preview

**Comment by Krisb239** [comment]
So what will happen is if you use the phone where there's a possibility of the box hitting something on the way down if it flips over and lands upside down the parachute won't despawn and it'll keep beeping and you can't target it. You can't flip it over at all either.

**Comment by cadburry6969** [comment]
> 

ok ill have to check that flipping thing other than that is it working fine?
